### PR TITLE
Update wales.md

### PR DESCRIPTION
**Pull request by o-s-warren**
They can't merge automatically - could you check?

### CODE REVIEW

**Review by BlueJessie — APPROVED** [review]
delete duplicates and wrong name Yr Wyddfa

**Review by o-s-warren — COMMENTED** [review]
You have misspelled 'Carnedd Llewelyn', and spelled it 'Google Facebook Mountain' - could you correct please?

**Review by o-s-warren — COMMENTED** [review]
Looks good@

**Review by BlueJessie — APPROVED** [review]
replace google facebook mountain with Carnedd Llewelyn

**Pull request merged**
